export { default as Facebook } from './facebook-svgrepo-com (1).svg'
export { default as Instagram } from './instagram-svgrepo-com.svg'
export { default as Twitter } from './twitter-svgrepo-com.svg'
export { default as Youtube} from './youtube-play-svgrepo-com.svg'
export { default as Close } from './close.svg'
export { default as Menu } from './menu.svg'
export { default as RightArrow } from './RightArrow.svg'
